### ISSUE TITLE
view jx 3.x boot jobs in the UI nicely

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/octant-jx#14]
so you can view the installation of Jenkins X 3.x from scratch via octant

**Comment by jstrachan** [comment]
its mostly working now - other than the `Manual Retrigger` doesn't work

**Comment by rawlingsj** [comment]
lets see how the kuberhealthy installation view looks

**Comment by jstrachan** [comment]
we can now at least view boot jobs in the admin UI
